hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("sh -c '[ -x /usr/libexec/xdg-desktop-portal-hyprland ] && exec /usr/libexec/xdg-desktop-portal-hyprland; [ -x /usr/lib/xdg-desktop-portal-hyprland ] && exec /usr/lib/xdg-desktop-portal-hyprland; true'")
    hl.exec_cmd("sh -c '[ -x /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 ] && exec /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1; [ -x /usr/libexec/policykit-1-gnome/polkit-gnome-authentication-agent-1 ] && exec /usr/libexec/policykit-1-gnome/polkit-gnome-authentication-agent-1; true'")
    hl.exec_cmd("hyprctl setcursor Adwaita 24")
    hl.exec_cmd("waybar -c ~/.config/hypr/waybar/config -s ~/.config/hypr/waybar/style.css")
    hl.exec_cmd("mako")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("sh -c 'command -v nm-applet >/dev/null && nm-applet --indicator'")
    hl.exec_cmd("hyprpaper --config ~/.config/hypr/hyprland/hyprpaper.conf")
end)
