general {
    layout = dwindle
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(88aaffee)
    col.inactive_border = rgba(333333aa)
}

dwindle {
#    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

gestures {
    workspace_swipe_distance = 300
    workspace_swipe_invert = true
    gesture = 3, horizontal, workspace
}

misc {
    disable_hyprland_logo = true
}

xwayland {
    force_zero_scaling = true
}

animations {
    enabled = true

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 5, myBezier
    animation = windowsOut, 1, 5, default
    animation = border, 1, 8, default
    animation = fade, 1, 5, default
    animation = workspaces, 1, 4, default
}
