splash = false

wallpaper {
    monitor = eDP-1
    path = /home/lct/Pictures/paris.png
    fit_mode = cover
}

wallpaper {
    monitor =
    path = /home/lct/Pictures/paris.png
    fit_mode = cover
}
